services:
  web:
    container_name: ikramov_uz  # Custom container name
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/app
      - ikramov_uz_data:/data  # Named volume
    env_file:
      - .env
    networks:
      - ikramov_uz_net  # Custom network

volumes:
  ikramov_uz_data:  # Volume declaration

networks:
  ikramov_uz_net: # Network declaration
    driver: bridge